@startUML
scale 3
title cl007开票记录
class "开票记录" as cl007 <007>
class "普通票" as cl007_1 <007_1>
class "专用票" as cl007_2 <007_2>

cl007 : 增值税专用发票代码
cl007 : 增值税专用发票号码
cl007 : 开票日期
cl007 : 购买方_名称
cl007 : 购买方_纳税人识别号
cl007 : 购买人_地址
cl007 : 购买人_电话
cl007 : 货物或应税劳务, 服务名称
cl007 : 规格型号
cl007 : 单位
cl007 : 数量
cl007 : 单价
cl007 : 金额
cl007 : 税率
cl007 : 税额
cl007 : 价格合计
cl007 : 销售方
cl007 : 收款人

cl007_2 : 增值税发票代码
cl007_2 : 增值税发票号码

cl007 --> cl007_1
cl007 --> cl007_2
@endUML