@startUML
scale 1024 width
title 阅读的四个层次
state 主题阅读 {
    state 分析阅读 {
        state 检视阅读 {
            state 基础阅读 {

            }
        }
    }
}
@endUML

@startUML
scale 1024 width
title 检视阅读
start
partition 确定是否值得读 {
    :先看书名页;
    if (有序)
        :看序;
    endif
    note left
        对类型进行简单的判断
    endnote
    :研究目录;
    note left
        研究这本书想说什么
    endnote
    if (有索引)
        :检阅索引;
    endif
    note left
        涵养的议题范围
        重要词汇
    endnote
    :读一下出版者的介绍;
}
partition 粗读 {
    :开始挑几个看起来和主题息息相关的主题篇章来读;
    :随意翻看, 不要太多;
    :将书从头到尾读一遍;
    note left
        不要停顿和倒退
        不要逐字读, 而要一目十行的读
    endnote
}
stop
@endUML

@startUML
scale 1024 width
title 做一个自我要求的读者
(做一个自我要求的读者要问的四个问题)
(做一个自我要求的读者要问的四个问题) --> (这本书说了啥)
(做一个自我要求的读者要问的四个问题) --> (这本书怎么说的)
(做一个自我要求的读者要问的四个问题) --> (这本书说的对不对)
(做一个自我要求的读者要问的四个问题) --> (这本书对我有什么启发)
@endUML

@startUML
scale 2048 width
title 笔记法
(笔记法)
(笔记法) ----> (记法)
(笔记法) --> (分类)

(分类) --> (问题笔记)
(分类) --> (结构笔记)
(分类) --> (辩证笔记)

(记法) --> (画底线)
(记法) --> (栏外线)
(记法) --> (星号或其它符号)
(记法) --> (空白处编号)
(记法) --> (空白处记下其它页码)
(记法) --> (圈出关键字)
(记法) --> (空白处做笔记)
(记法) --> (整体框架)
@endUML

@startUML
scale 2048 width
title 分析阅读
start
partition 找出一本书在谈什么 {
    :依照书的各类进行分类;
    :使用简短文字说明整本书在谈论什么;
    :将书的主要部分按顺序列出来, 并梳理大纲;
    :确定作者想要解决的问题;
}
partition 诠释一本书的内容 {
    :诠释作者的关键字, 与作者达成共识;
    :由最重要的句子, 抓住作者的主旨;
    :找到论证和结论;
    :确定未解决的问题;
}
partition 评论一本书 {
    fork
        :智慧礼节的一般规则;
            :除非你已经完成大纲架构, 并且已经能诠释本书了, 否则不要轻易评论;
            :不要争强好胜, 非辩到底不可;
            :在说出评论之前, 你能区别得出真正的知识和个人观点;
    fork again
        :批评观点的特别标准, (什么样的批评是有益的);
            :证明作者的知识不足;
            :证明作者的知识错误;
            :证明作者的不合逻辑;
            :证明作者的分析和理由是不完整的;
    end fork
}
stop

@endUML

@startUML
scale 1024 width
title 书的分类
class "书" as book
class b1 as "理论性的书"{
    强调知识的传递
}
class b2 as "实用性的书"{
    强调知识的应用
    以 ".. 的方法" "如何 .." 为名
}
class b2_1 as "指南类的书" {

}
class b2_1_1 as "规范类的书" {

}
class b2_2 as "演说类的书" {

}
class b1_1 as "科学" {
    科学关注永恒
    科学关注特殊的事
    主要使用观察的方法
}
class b1_2 as "历史" {
    历史关注过去
}
class b1_3 as "哲学" {
    哲学关注日常的事
    主要使用思考的方法
}
book <|-- b1
book <|-- b2
b1 <|-- b1_1
b1 <|-- b1_2
b1 <|-- b1_3

b2 <|-- b2_1
b2 <|-- b2_2
b2 <|-- b2_1_1

@endUML

@startUML
scale 1024 width
title 注意下面这些可能是关键字
(作者以任何方式强调的词)
(专业词汇)
(用法奇怪的词)
(作者与他人争执的词)
(作者用来诠释主旨的概念)
@endUML

@startUML
scale 1024 width
title 主题阅读
start
partition 准备阶段 {
    :设计书目;
    note left
        可选的方案:
        图书馆目录;
        专家建议;
        书中的书目索引;
    end note
    :对上述书目上的书进行检视阅读, 产生一个概观;
}
partition 阅读阶段 {
    :找出主题相关章节;
    :找出中立词汇;
    :建立中立主旨;
    note left
        列出主旨相关的问题, 让不同的作者来回答
    end note
    :界定主要议题和次要议题;
    note left
        列出不同作者对不同议题的看法;
        当然有的作者可能对有的议题根本不感兴趣;
    end note
    :分析, 排列, 比较这些问题并对它们进行;
}
stop
@endUML
