@startuml
actor foo1 as a
boundary foo2 as b
control foo3 as c
entity foo4 as d
database foo5 as e
participant foo6 as f

a --> b: text
b --> c: text
d --> e: text
e --> f: text
@enduml

@startuml this is a test
left to right direction
actor 消费者
actor 销售员
rectangle 买单 {
消费者 -- (买单)
(买单) .> (付款) : include
(帮助) .> (买单) : extends
(买单) -- 销售员
}

@enduml

@startuml
    a -> b -> c -> d -> e

@enduml

@startuml
scale 500*500
start
:"分享工具：plantuml";
if (你需要吗?) then (需要)
    :"花1个小时";
    :"有帮助";
    stop
else (不需要)
    :"有visio就够了";
    stop
endif

caption figure 1.2 test
@enduml

@startuml

(*) --> "Initialisation"

  if " Some Test" then
    -->[ture] "Some Activity"
    --> "Another Activity"
    -right-> (*)
  else
    ->[false] "Something else"
    -->[Ending process] (*)
  endif

@enduml

@startuml
testdot
@enduml