@startuml
scale 3
title 当前用户
class "当前用户" as cl000 <cl000>{
    用户唯一账号
    用户身份
    用户状态
}
@enduml

@startuml
scale 3
title 企业
class "企业" as cl001 <cl001>{
    唯一标识
    账号
    手机号
    登录密码
    交易密码
    企业名称
    企业LOGO
    企业授权声明
    账户
    所属行业
    提供材料
    企业简介
    企业类型
    工商登录号
    商业执照注册号
    单位所在地
    住所
    经营模式
    主营业务
    经营范围
    有效期
    注册时间
    注册金额
    单位电话
    邮编
    通信地址
    企业信息来源
    法人姓名
    法人归属地
    法人电话
    法人身份证号
    证件有效期
    身份证类型
    身份证图片
    企业法人营业执照
    企业证照
    组织机构代码证
}
@enduml

@startuml
scale 3
title 企业证照
class "企业证照" as cl002 <cl002>{
    唯一标识
    证照名称
    证照简介
    证照图片
    企业唯一标识
}
@enduml