@startsalt
{
    {T
        + 顶部
        ++ 热线电话
        ++ 用户提示
        +++ 登录提示
        ++++ 欢迎词
        ++++ 登录按钮
        +++ 用户提示
        ++++ 快速发布按钮
        +++++ 快速发布按钮组
        ++++++ 发布商品
        ++++++ 发布求购
        ++++ 欢迎词
        ++++ 安全退出按钮
        ++++ 
    }
}
@endsalt