@startUML
title 区块链认证方案流程
participant 惠智区块链 as hz
==创建区块链身份==
-> hz: 调用 [创建区块链身份] 接口
hz -> hz: 创建地址与私钥
<-- hz: 返回地地址与私钥
==验证区块链身份==
-> hz: 调用 [验证区块链身份] 接口
hz -> hz: 激活地址
<-- hz: 返回激活结果
@endUML