@startUML
scale 3
title 定金-尾款-解冻流程示意
|买方操作|
start
:买方下单;
:买方支付定金;
|买方账户|
:买方账户向卖方账户转入定金;
|卖方账户|
:卖方账户冻结定金;
|买方操作|
fork 
:买方现金支付尾款;
fork again
:买方融资支付尾款;
end fork
|买方账户|
:买方账户向卖方账户转入尾款;
|卖方账户|
:卖方账户冻结尾款;
|卖方操作|
:卖方发货;
|买方操作|
:买方验收;
|后台操作|
:财务人员解冻货款;
|卖方账户|
:卖方账户解决定金与尾款;
end
@endUML