@startUML
scale 3
title 基础闭环
start
:后台登录;
:新增供求用户;
:发布出售信息;
:后台审核;
:上架;
:新增供求用户;
:充值;
:选择规格;
:询报价;
:下单;
:付款;
end
@endUML

@startUML
scale 3
title 用例
(uc001新增用户)
(uc002用户认证)
(uc003发布出售信息)
(uc004)
@endUMl

后台登录：

合法性验证:
1 没有位数的限制

密码:
合法性验证：
无

后台导航:
根据权限控制可见项


角色: 可重名
首页: 基础权限
超级管理员: 可删除

系统参数: 排序/筛选/显示内容

消息设置: 


新增用户：
账号: 有校验, 手机号
类型: 有问题, 可多选
企业类型: 联动的内容?
法人身份: 应该加上传限制

融资用户:
融资用户可录入, 但不显示

认证: 
1 不认证, 前台可以发商品, 后台不可以发


商品属性:
1 可以显示不完全的属性

3 事件??

属性 价格, 加到原价上

审核: 审核失败

修改后直接上架

修改商品后商品不会有任何变化

前台:
已上架的, 已过期, 已售完

商品图片问题

查看详细的展示字段

订单消息(买卖双方的)

订单状态, 交易状态问题

订单详情, 显示id 

交易状态???


过期, 联系客服

确认没有时间限制

前台商品列表以发面时间, 状态


实名认证 通过了不能编辑

编辑之后不能认证

不能过, 也可以授信

发起账户, 

记录 不是从

提现



融资 审核通过后 4 天结束时间



融资未满标 冻结 冻到哪里去了

后台满标和截标没有用


还

打款 点否没有用

逾期后不得发起融资

资金记录 总金额计算方法

逾期利息
ip

两个属性, 

@startUMl
scale 3
title 商品状态机
state "001待审核" as st001
state "002上架"  as st002
state "003下架" as st003
state "004已售罄" as st004
state "005已过期" as st005
state "006审核失败" as st006

[*] -> st001: 新增用户
st001 --> st002: 审核通过
st001 -> st006: 审核不通过
st006 -> st001: 修改用户
st002 --> st003: 下架
st003 -> st002: 上架
st002 -left-> st004: 售罄
st002 -> st005: 过期
st003 -> st005: 过期
st001 --> st005: 过期
st006 --> st005: 过期

st004 ---> [*]

st005 ---> [*]


st001 : 不显示在供货专区及求购专区内
st001 : 可以进行修改
st001 : 可以进行审核
st001 : 不可对此商品生成订单

st006 : 不显示在供货专区及求购专区内
st006 : 可以进行修改
st006 : 不可进行审核
st006 : 不可对对此商品生成订单

st002 : 显示在供货专区或求购专区
st002 : 不可在前台进行修改
st002 : 可以对此商品进行询价及下单
st002 : 可以对此商品进行架

st003 : 不显示在供货专区或求购专区
st003 : 不可在前台进行修改
st003 : 不可进行审核
st003 : 不可对此商品进行询报价下单

st004 : 可以显示在供货专区及求购专区, 显示状态为关闭
st004 : 不可在前台进行修改
st004 : 不可进行审核
st004 : 不可对此商品进行询报价及下单

st005 : 可以显示在供货专区及求购专区, 显示状态为关闭
st005 : 不可在前台进行修改
st005 : 不可进行审核
st005 : 不可对此商品进行询报价及下单
@endUMl

@startUML
scale 3
title 订单状态机
state "001待支付" as st001
state "002待支付尾款" as st002
state "003已取消" as st003
state "004待发货" as st004
state "005待验收" as st005
state "006已完成" as st006
state "007已评价" as st007
state "008退款中" as st008
state "009已退款" as st009
state "010已关闭" as st010
state "004_1提醒发货" as st004_1
state "002_1融资中" as st002_1

[*] --> st001: 买方下单
st001 --> st002: 买方支付定金
st002 --> st004: 买方支付尾款
st004 --> st005: 卖方发货
st005 --> st006: 买方验收
st006 --> st007: 双方订单(本期无此流程)

st002 -left-> st008: 买方申请退款(本期无此流程)
st004 -left-> st008: 买方申请退款(本期无此流程)
st005 -left-> st008: 买方申请退款(本期无此流程)

st008 --> st009: 完成退款操作
st009 --> st010: 完成退款操作

st001 -> st003: 用户取消订单(本期无此流程)

st004 --> st004_1: 买方提醒发货
st004_1 -left-> st005:卖方发货

st002 -> st002_1: 买方发起融资
st002_1 --> st004: 融资标的满标
st002_1 -left-> st002: 融资标的审核不通过

st006 -> [*]

st001 : 订单显示:"现阶段: 支付定金" 及 "待付款"
st001 : 销售订单显示: 付款按钮
st001 : 点击销售订单付款按钮, 跳转支付定金页面

st002 : 订单显示: "现阶段: 支付尾款" 及 "待付款"
st002 : 销售订单显示: 付款按钮
st002 : 点击销售订单付款按钮, 跳转支付尾款页面
st002 : 点击销售订单付款按钮, 跳转支付尾款页面
st002 : 可以基于此订单进行融资

st003 : 本期无此状态

st004 : 订单显示: "现阶段: 等待发货" 及 "待发货"
st004 : 销售订单显示: 提醒发货按钮
st004 : 采购订单显示: 发货按钮

st004_1 : 订单显示: "现阶段: 等待发货" 及 "待发货"
st004_1 : 销售订单隐藏提醒发货按钮
st004_1 : 采购订单显示: 发货按钮

st002_1 : 订单显示: "现阶段: 等待发货" 及 "待发货"
st002_1 : 销售订单显示禁用的 "融资中" 按钮

st005 : 订单显示: "现阶段: 等待验收" 及 "待验收"
st005 : 销售订单显示: 验收按钮

st006 : 订单显示: "现阶段: 完成" 及 "完成"

st007 : 本期无此状态

st008 : 本期无此状态

st009 : 本期无此状态

st010 : 本期无此状态 
@endUML

@startUMl
scale 3
title 融资标的状态机
state "001待审核" as st001
state "002审核不通过" as st002
state "003募集中" as st003
state "004募集失败" as st004
state "005待还款" as st005
state "006已还款" as st006
state "007已逾期" as st007

[*] --> st001: 买方发起融资支付尾款
st001 --> st003: 审核通过
st003 --> st005: 标的满标
st005 --> st006: 还本付息

st001 -> st002: 审核不通过
st003 -left-> st004: 在投标结束时间内没有满标(本期无此流程)
st005 -> st007: 逾期未还本付息

st004 --> st005: 手动满标

st007 --> st006: 还本付息

st002 -----> [*]
st006 --> [*]
st004 ----> [*]

st001 : 相应的采购订出现禁用的 "融资中按钮"
st001 : 该标的出现在后台 "初审列表" 中

st002 : 相应的采购订单回退到 "待支付尾款" 状态
st002 : 该标的出现在后台 "审核未通过" 列表中

st003 : 相应的采购订单出现禁用的 "融资中按钮"
st003 : 该标的出现在后台 "募集中的标列表" 中

st004 : 本期无此状态

st005 : 该标的出现在后台 "还款中列表" 中

st006 : 该标的出现在后台 "已还款列表" 中

st007 : 该标的出现在后台 "已逾期列表" 中
@endUMl

@startUML
scale 3
title 投资状态机
state "001投标中" as st001
state "002还款中" as st002
state "003已完成" as st003

[*] --> st001: 融资用户进行投资
st001 --> st002: 融资标的满标
st002 --> st003: 借款人还本付息
st003 --> [*]
@endUML


@startUML
scale 3
title 询报价流程
start
:用户发起询报价聊天;
if (聊天类型) then (询价聊天)
:在成交下单区设置下单价格为初始价格, 下单数量为 1;
else (报价聊天)
:成成交下单区设置成效价格为初始价格, 下单数量为剩余数量;
endif
repeat
if (买方是否下单) then (是)
:生成订单, 订单价格为下单区的下单价格, 下单数量为下单区下单数量;
end
elseif (卖方是否成交) then (是)
:更新对方下单区的下单价格为成交价格, 下单数量为成交数量;
elseif (卖方发送) then (是)
:更新对对方下单区的下单价格为发送价格, 下单数量为发送数量;
else (买方发送)
:更新对方成交区的成交价格为发送价格, 成交数量发送数量;
endif
@endUML

@startUML
scale 3
title 整体流程
(uc001录入用户) as uc001
(uc002快速发布) as uc002
(uc003确定价格) as uc003
(uc004完成订单) as uc004
@endUML