@startUML
scale 3
title 主线闭环流程
start
repeat
    :用户消费;
    :用户获得积分;
    :用户购买卡券;
    :用户使用卡券;
repeat while
stop
@endUML

@startUML
scale 3
top to bottom direction
title 主要对象
class "积分" as points
class "卡券" as card
class "用户" as user
class "支付渠道" as zf
package 规则 {
    class "规则" as rule
    class "推荐规则" as rule_tj
    class "提醒规则" as rule_tx
    class "积分结算规则" as rule_js_p
    class "卡券结算规则" as rule_js_c
    class "积分发放规则" as rule_ff
}
package 商家 {
    class "商家" as B
    class "积分发放商" as B_p
    class "卡券发行商" as B_c
}

rule <|-- rule_tj
rule <|-- rule_tx
rule <|-- rule_js_c
rule <|-- rule_js_p
rule <|-- rule_ff

B <|-- B_p
B <|-- B_c
@endUML